# COLOR DEFINITIONS
BG_COLOR = (30, 30, 30)
GRID_COLOR = (0, 0, 255)
GHOST_COLOR = (255, 0, 255)
PACMAN_COLOR = (255, 255, 0)
COIN_COLOR = (200, 200, 0)

#SIZE OF SCREEN
WIDTH = 1000
HEIGHT = 550

# SIZE OF BLOCK
BLOCK = 50
BLOCKS_WIDTH = WIDTH // BLOCK
BLOCKS_HEIGHT = HEIGHT // BLOCK

# TIMES
STEP_TIME = 0.5
FPS = 10
SPAWN_COIN_TIME = 1

# BORDER INDEXES
LEFT_INDEX = 0
RIGHT_INDEX = 19
TOP_INDEX = 0
BOTTOM_INDEX = 10

# POINTS
INC_POINTS = 2
DCS_POINTS = 5

# DEFAULT POSITIONS
GHOST1_X = 1
GHOST1_Y = 1

GHOST2_X = TOP_INDEX + 1
GHOST2_Y = RIGHT_INDEX - 1

GHOST3_X = BOTTOM_INDEX - 1
GHOST3_Y = 1

GHOST4_X = BOTTOM_INDEX - 1
GHOST4_Y = RIGHT_INDEX - 1

PACMAN_X = 9
PACMAN_Y = 5